language: node_js
node_js:
- stable
script:
- npm run ci
deploy:
  provider: gcs
  access_key_id: GOOG7KQQ4DPPRHWEOTAXINYH
  secret_access_key:
    secure: PR+HKnIqTI1mmQ9RUo1e4bWgxxzi8v7TVvhhyc61dSCcjXlHfBQ94aMg/AGBEo1H62LwqfFIVwqf9TBS9EVcdZ93D6gLgDc1XMxH9YpyeLP2MBRRHcsivh6Vp+cLbtKIroCeLHu5bY8quRWcKGmx+7xSZmBTLEMgLTIkZbAEqqcNMX4zBUmIekhaqC0xihjL4JAoUc8NLDk3JncT6oOlMvrdF8lJRC35JULNm59L5FAdNZHav5XdQt8c9aL+hlOv7H8jh1BTwTVOR1ADjaeL2O1Fy3DxMMtO8Sw6KYMRFip5VPaVbAGDbFzGj+8VDvZEPuVmR2b8OMlL1oP9nsNU4eRmbKlWuEFV7NffrQCwO0bkbWfnNc8vqgNri2xpDFzNyi4OnxE/Q3QquKVbX54vdM1sU1vQvz6p7wBchSBqqUdxojaI0p7WJAbMqrIN08qUFpo2uLEo1wUcZaSzAuaCjdCGhFFQSwXhu2DP+BiR1yVwt7As1wJ960rU1i1u5Lq0ckD8iKfdgt4aNoPN/jGJ9aTKp1FPb1e+sgvKOqqZ8tZO235/IYBRK/8xL4ANFSR4dXUXh7tVEYNBS3FpmqBaUJ33/pj3YLMER8mOdPFk1EEAexibU8aEe/ZMRB/pkXaMolDppOxLn4j3Zc0yJCa1H1nEb5SaLeIpUZT68GEGZ5A=
  bucket: fukuoka.gocon.jp
  skip_cleanup: true
  local-dir: dist
  on:
    branch: master
notifications:
  slack: fukuokago:sNzKUS8uVK0biPlNoEU0AwIl
  email: false
